// <auto-generated />
using System;
using GreenKeeper.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenKeeper.Migrations
{
    [DbContext(typeof(GreenKeeperDbContext))]
    [Migration("20260724111537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("GreenKeeper.Models.CareSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Care")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalUnit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCaredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "Care")
                        .IsUnique();

                    b.ToTable("CareSchedules");
                });

            modelBuilder.Entity("GreenKeeper.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GreenKeeper.Models.SunlightRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("SunlightRequirements");
                });

            modelBuilder.Entity("GreenKeeper.Models.CareSchedule", b =>
                {
                    b.HasOne("GreenKeeper.Models.Plant", "SelectedPlant")
                        .WithMany("CareSchedules")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedPlant");
                });

            modelBuilder.Entity("GreenKeeper.Models.SunlightRequirement", b =>
                {
                    b.HasOne("GreenKeeper.Models.Plant", "SelectedPlant")
                        .WithOne("SunlightRequirement")
                        .HasForeignKey("GreenKeeper.Models.SunlightRequirement", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectedPlant");
                });

            modelBuilder.Entity("GreenKeeper.Models.Plant", b =>
                {
                    b.Navigation("CareSchedules");

                    b.Navigation("SunlightRequirement");
                });
#pragma warning restore 612, 618
        }
    }
}
